# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - commit-message:
      prefix: 'chore'
    directory: '/'
    labels: ['dependabot']
    open-pull-requests-limit: 5
    package-ecosystem: 'npm'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '15:00'
    target-branch: 'chore/dependabot'

  - commit-message:
      prefix: 'ci'
    directory: '/'
    labels: ['dependabot', 'github-actions']
    open-pull-requests-limit: 3
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '15:00'
    target-branch: 'chore/dependabot'
