name: Reusable Workflows

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  pr-title-check:
    name: Check PR for semantic title
    uses: mParticle/mparticle-workflows/.github/workflows/pr-title-check.yml@stable
  pr-branch-target-continuous:
    name: Check PR for semantic target branch
    uses: mParticle/mparticle-workflows/.github/workflows/pr-branch-target-continuous.yml@stable
  security-lint-checks:
    name: Security Lint Checks
    uses: mparticle/mparticle-workflows/.github/workflows/security-checks.yml@stable
    with:
      base_branch: 'main'
