name: Design Tokens to CSS

on:
  push:
    branches-ignore:
      - "main"
      - "development"
  workflow_dispatch:

jobs:
  design-tokens-to-css:
    name: Build CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM install
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Run NPM tokens-to-css
        run: npm run tokens-to-css

      - name: Commit generated CSS
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit generated CSS
